/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutUserManagementIndexImport } from './routes/_layout/user-management/index'
import { Route as LayoutUnauthorisedIndexImport } from './routes/_layout/unauthorised/index'
import { Route as LayoutSimpleUploadIndexImport } from './routes/_layout/simple-upload/index'
import { Route as LayoutPromptManagementIndexImport } from './routes/_layout/prompt-management/index'
import { Route as LayoutProfileIndexImport } from './routes/_layout/profile/index'
import { Route as LayoutAudioUploadIndexImport } from './routes/_layout/audio-upload/index'
import { Route as LayoutAudioRecordingsIndexImport } from './routes/_layout/audio-recordings/index'
import { Route as LayoutAdminIndexImport } from './routes/_layout/admin/index'
import { Route as LayoutAudioRecordingsIdImport } from './routes/_layout/audio-recordings/$id'
import { Route as LayoutAudioRecordingsSharedIndexImport } from './routes/_layout/audio-recordings/shared/index'
import { Route as LayoutAdminUserManagementIndexImport } from './routes/_layout/admin/user-management/index'
import { Route as LayoutAdminDeletedJobsIndexImport } from './routes/_layout/admin/deleted-jobs/index'
import { Route as LayoutAdminAllJobsIndexImport } from './routes/_layout/admin/all-jobs/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutUserManagementIndexRoute = LayoutUserManagementIndexImport.update({
  id: '/user-management/',
  path: '/user-management/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUnauthorisedIndexRoute = LayoutUnauthorisedIndexImport.update({
  id: '/unauthorised/',
  path: '/unauthorised/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSimpleUploadIndexRoute = LayoutSimpleUploadIndexImport.update({
  id: '/simple-upload/',
  path: '/simple-upload/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPromptManagementIndexRoute =
  LayoutPromptManagementIndexImport.update({
    id: '/prompt-management/',
    path: '/prompt-management/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutProfileIndexRoute = LayoutProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAudioUploadIndexRoute = LayoutAudioUploadIndexImport.update({
  id: '/audio-upload/',
  path: '/audio-upload/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAudioRecordingsIndexRoute = LayoutAudioRecordingsIndexImport.update(
  {
    id: '/audio-recordings/',
    path: '/audio-recordings/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutAdminIndexRoute = LayoutAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAudioRecordingsIdRoute = LayoutAudioRecordingsIdImport.update({
  id: '/audio-recordings/$id',
  path: '/audio-recordings/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAudioRecordingsSharedIndexRoute =
  LayoutAudioRecordingsSharedIndexImport.update({
    id: '/audio-recordings/shared/',
    path: '/audio-recordings/shared/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAdminUserManagementIndexRoute =
  LayoutAdminUserManagementIndexImport.update({
    id: '/admin/user-management/',
    path: '/admin/user-management/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAdminDeletedJobsIndexRoute =
  LayoutAdminDeletedJobsIndexImport.update({
    id: '/admin/deleted-jobs/',
    path: '/admin/deleted-jobs/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAdminAllJobsIndexRoute = LayoutAdminAllJobsIndexImport.update({
  id: '/admin/all-jobs/',
  path: '/admin/all-jobs/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/audio-recordings/$id': {
      id: '/_layout/audio-recordings/$id'
      path: '/audio-recordings/$id'
      fullPath: '/audio-recordings/$id'
      preLoaderRoute: typeof LayoutAudioRecordingsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/audio-recordings/': {
      id: '/_layout/audio-recordings/'
      path: '/audio-recordings'
      fullPath: '/audio-recordings'
      preLoaderRoute: typeof LayoutAudioRecordingsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/audio-upload/': {
      id: '/_layout/audio-upload/'
      path: '/audio-upload'
      fullPath: '/audio-upload'
      preLoaderRoute: typeof LayoutAudioUploadIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/profile/': {
      id: '/_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/prompt-management/': {
      id: '/_layout/prompt-management/'
      path: '/prompt-management'
      fullPath: '/prompt-management'
      preLoaderRoute: typeof LayoutPromptManagementIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/simple-upload/': {
      id: '/_layout/simple-upload/'
      path: '/simple-upload'
      fullPath: '/simple-upload'
      preLoaderRoute: typeof LayoutSimpleUploadIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/unauthorised/': {
      id: '/_layout/unauthorised/'
      path: '/unauthorised'
      fullPath: '/unauthorised'
      preLoaderRoute: typeof LayoutUnauthorisedIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/user-management/': {
      id: '/_layout/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof LayoutUserManagementIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/all-jobs/': {
      id: '/_layout/admin/all-jobs/'
      path: '/admin/all-jobs'
      fullPath: '/admin/all-jobs'
      preLoaderRoute: typeof LayoutAdminAllJobsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/deleted-jobs/': {
      id: '/_layout/admin/deleted-jobs/'
      path: '/admin/deleted-jobs'
      fullPath: '/admin/deleted-jobs'
      preLoaderRoute: typeof LayoutAdminDeletedJobsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/user-management/': {
      id: '/_layout/admin/user-management/'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof LayoutAdminUserManagementIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/audio-recordings/shared/': {
      id: '/_layout/audio-recordings/shared/'
      path: '/audio-recordings/shared'
      fullPath: '/audio-recordings/shared'
      preLoaderRoute: typeof LayoutAudioRecordingsSharedIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAudioRecordingsIdRoute: typeof LayoutAudioRecordingsIdRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAudioRecordingsIndexRoute: typeof LayoutAudioRecordingsIndexRoute
  LayoutAudioUploadIndexRoute: typeof LayoutAudioUploadIndexRoute
  LayoutProfileIndexRoute: typeof LayoutProfileIndexRoute
  LayoutPromptManagementIndexRoute: typeof LayoutPromptManagementIndexRoute
  LayoutSimpleUploadIndexRoute: typeof LayoutSimpleUploadIndexRoute
  LayoutUnauthorisedIndexRoute: typeof LayoutUnauthorisedIndexRoute
  LayoutUserManagementIndexRoute: typeof LayoutUserManagementIndexRoute
  LayoutAdminAllJobsIndexRoute: typeof LayoutAdminAllJobsIndexRoute
  LayoutAdminDeletedJobsIndexRoute: typeof LayoutAdminDeletedJobsIndexRoute
  LayoutAdminUserManagementIndexRoute: typeof LayoutAdminUserManagementIndexRoute
  LayoutAudioRecordingsSharedIndexRoute: typeof LayoutAudioRecordingsSharedIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAudioRecordingsIdRoute: LayoutAudioRecordingsIdRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAudioRecordingsIndexRoute: LayoutAudioRecordingsIndexRoute,
  LayoutAudioUploadIndexRoute: LayoutAudioUploadIndexRoute,
  LayoutProfileIndexRoute: LayoutProfileIndexRoute,
  LayoutPromptManagementIndexRoute: LayoutPromptManagementIndexRoute,
  LayoutSimpleUploadIndexRoute: LayoutSimpleUploadIndexRoute,
  LayoutUnauthorisedIndexRoute: LayoutUnauthorisedIndexRoute,
  LayoutUserManagementIndexRoute: LayoutUserManagementIndexRoute,
  LayoutAdminAllJobsIndexRoute: LayoutAdminAllJobsIndexRoute,
  LayoutAdminDeletedJobsIndexRoute: LayoutAdminDeletedJobsIndexRoute,
  LayoutAdminUserManagementIndexRoute: LayoutAdminUserManagementIndexRoute,
  LayoutAudioRecordingsSharedIndexRoute: LayoutAudioRecordingsSharedIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/audio-recordings': typeof LayoutAudioRecordingsIndexRoute
  '/audio-upload': typeof LayoutAudioUploadIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/prompt-management': typeof LayoutPromptManagementIndexRoute
  '/simple-upload': typeof LayoutSimpleUploadIndexRoute
  '/unauthorised': typeof LayoutUnauthorisedIndexRoute
  '/user-management': typeof LayoutUserManagementIndexRoute
  '/admin/all-jobs': typeof LayoutAdminAllJobsIndexRoute
  '/admin/deleted-jobs': typeof LayoutAdminDeletedJobsIndexRoute
  '/admin/user-management': typeof LayoutAdminUserManagementIndexRoute
  '/audio-recordings/shared': typeof LayoutAudioRecordingsSharedIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/audio-recordings': typeof LayoutAudioRecordingsIndexRoute
  '/audio-upload': typeof LayoutAudioUploadIndexRoute
  '/profile': typeof LayoutProfileIndexRoute
  '/prompt-management': typeof LayoutPromptManagementIndexRoute
  '/simple-upload': typeof LayoutSimpleUploadIndexRoute
  '/unauthorised': typeof LayoutUnauthorisedIndexRoute
  '/user-management': typeof LayoutUserManagementIndexRoute
  '/admin/all-jobs': typeof LayoutAdminAllJobsIndexRoute
  '/admin/deleted-jobs': typeof LayoutAdminDeletedJobsIndexRoute
  '/admin/user-management': typeof LayoutAdminUserManagementIndexRoute
  '/audio-recordings/shared': typeof LayoutAudioRecordingsSharedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/audio-recordings/$id': typeof LayoutAudioRecordingsIdRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/audio-recordings/': typeof LayoutAudioRecordingsIndexRoute
  '/_layout/audio-upload/': typeof LayoutAudioUploadIndexRoute
  '/_layout/profile/': typeof LayoutProfileIndexRoute
  '/_layout/prompt-management/': typeof LayoutPromptManagementIndexRoute
  '/_layout/simple-upload/': typeof LayoutSimpleUploadIndexRoute
  '/_layout/unauthorised/': typeof LayoutUnauthorisedIndexRoute
  '/_layout/user-management/': typeof LayoutUserManagementIndexRoute
  '/_layout/admin/all-jobs/': typeof LayoutAdminAllJobsIndexRoute
  '/_layout/admin/deleted-jobs/': typeof LayoutAdminDeletedJobsIndexRoute
  '/_layout/admin/user-management/': typeof LayoutAdminUserManagementIndexRoute
  '/_layout/audio-recordings/shared/': typeof LayoutAudioRecordingsSharedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/audio-recordings/$id'
    | '/admin'
    | '/audio-recordings'
    | '/audio-upload'
    | '/profile'
    | '/prompt-management'
    | '/simple-upload'
    | '/unauthorised'
    | '/user-management'
    | '/admin/all-jobs'
    | '/admin/deleted-jobs'
    | '/admin/user-management'
    | '/audio-recordings/shared'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/audio-recordings/$id'
    | '/admin'
    | '/audio-recordings'
    | '/audio-upload'
    | '/profile'
    | '/prompt-management'
    | '/simple-upload'
    | '/unauthorised'
    | '/user-management'
    | '/admin/all-jobs'
    | '/admin/deleted-jobs'
    | '/admin/user-management'
    | '/audio-recordings/shared'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/audio-recordings/$id'
    | '/_layout/admin/'
    | '/_layout/audio-recordings/'
    | '/_layout/audio-upload/'
    | '/_layout/profile/'
    | '/_layout/prompt-management/'
    | '/_layout/simple-upload/'
    | '/_layout/unauthorised/'
    | '/_layout/user-management/'
    | '/_layout/admin/all-jobs/'
    | '/_layout/admin/deleted-jobs/'
    | '/_layout/admin/user-management/'
    | '/_layout/audio-recordings/shared/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/audio-recordings/$id",
        "/_layout/admin/",
        "/_layout/audio-recordings/",
        "/_layout/audio-upload/",
        "/_layout/profile/",
        "/_layout/prompt-management/",
        "/_layout/simple-upload/",
        "/_layout/unauthorised/",
        "/_layout/user-management/",
        "/_layout/admin/all-jobs/",
        "/_layout/admin/deleted-jobs/",
        "/_layout/admin/user-management/",
        "/_layout/audio-recordings/shared/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/audio-recordings/$id": {
      "filePath": "_layout/audio-recordings/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/": {
      "filePath": "_layout/admin/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/audio-recordings/": {
      "filePath": "_layout/audio-recordings/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/audio-upload/": {
      "filePath": "_layout/audio-upload/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/profile/": {
      "filePath": "_layout/profile/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/prompt-management/": {
      "filePath": "_layout/prompt-management/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/simple-upload/": {
      "filePath": "_layout/simple-upload/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/unauthorised/": {
      "filePath": "_layout/unauthorised/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/user-management/": {
      "filePath": "_layout/user-management/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/all-jobs/": {
      "filePath": "_layout/admin/all-jobs/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/deleted-jobs/": {
      "filePath": "_layout/admin/deleted-jobs/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/user-management/": {
      "filePath": "_layout/admin/user-management/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/audio-recordings/shared/": {
      "filePath": "_layout/audio-recordings/shared/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
